AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  vpcId:
    Type: String
    Default: vpc-258b1d5d
  subnetId:
    Type: String
    Default: subnet-7d818c36
  amiId:
    Type: String
    Default: ami-0b1e2eeb33ce3d66f
  keyName:
    Type: String
    Default: my-key


Resources:

  AppVolume:
    Type: AWS::EC2::Volume
    DeletionPolicy: Snapshot
    Properties:
      AvailabilityZone: us-west-2a
      Size: 1
      Tags:
        -
          Key: Name
          Value: app-volume
      VolumeType: gp2


  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Web server
      GroupName: web
      VpcId: !Ref vpcId
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        -
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0


  ## EC2 Instance with a custom security group
  ## and a larger root instance device
  ## and an externally created EBS volume attached
  WebInstance:
    Type: AWS::EC2::Instance
    Properties:
#      BlockDeviceMappings:
#        -
#          DeviceName: "/dev/xvda"
#          Ebs:
#            VolumeSize: 8
#            VolumeType: gp2
#            DeleteOnTermination: true
      InstanceType: t2.micro
      ImageId: !Ref amiId
      KeyName: !Ref keyName
      Monitoring: true
      SecurityGroupIds:
        - !Ref WebSecurityGroup
      SubnetId: !Ref subnetId
#      RoleName: !Ref roleName
      Tags:
        -
          Key: Name
          Value: webserver
        -
          Key: component
          Value: aws_samples

      Volumes:
        -
          Device: "/dev/sdh"
          VolumeId: !Ref   AppVolume
      UserData:
        "Fn::Base64": !Sub |
          #!/bin/bash -xe
          sleep 20
          sudo su
          yum update -y
          yum install -y httpd.x86_64
          systemctl start httpd.service
          systemctl enable httpd.service
          rm -rf /var/www/html
          # Format /dev/xvdh if it does not contain a partition yet
          if [ "$(file -b -s /dev/xvdh)" == "data" ]; then
            mkfs -t ext4 /dev/xvdh
          fi
          mkdir -p /var/www/html
          mount /dev/xvdh /var/www/html
          # Persist the volume in /etc/fstab so it gets mounted again
          echo '/dev/xvdh /var/www/html ext4 defaults,nofail 0 2' >> /etc/fstab
          echo "Hello AWS World" > /var/www/html/index.html


  ElasticIp:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref WebInstance
      Domain: vpc
